// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package com.thanos.api.proto.broadcast;

public interface DefaultResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.broadcast.DefaultResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   * @return The result.
   */
  boolean getResult();
}
