// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package com.thanos.api.proto.broadcast;

public interface DefaultRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.broadcast.DefaultRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string param = 1;</code>
   * @return The param.
   */
  java.lang.String getParam();
  /**
   * <code>string param = 1;</code>
   * @return The bytes for param.
   */
  com.google.protobuf.ByteString
      getParamBytes();
}
