// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package com.thanos.api.proto.broadcast;

public interface EthTransactionsBroadcastDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
   */
  java.util.List<com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO> 
      getTxsList();
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
   */
  com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO getTxs(int index);
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
   */
  int getTxsCount();
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
   */
  java.util.List<? extends com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTOOrBuilder> 
      getTxsOrBuilderList();
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
   */
  com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTOOrBuilder getTxsOrBuilder(
      int index);
}
