// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package com.thanos.api.proto.broadcast;

/**
 * Protobuf type {@code com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO}
 */
public final class EthTransactionsBroadcastDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO)
    EthTransactionsBroadcastDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EthTransactionsBroadcastDTO.newBuilder() to construct.
  private EthTransactionsBroadcastDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EthTransactionsBroadcastDTO() {
    txs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EthTransactionsBroadcastDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EthTransactionsBroadcastDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              txs_ = new java.util.ArrayList<com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO>();
              mutable_bitField0_ |= 0x00000001;
            }
            txs_.add(
                input.readMessage(com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        txs_ = java.util.Collections.unmodifiableList(txs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_EthTransactionsBroadcastDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_EthTransactionsBroadcastDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.class, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.Builder.class);
  }

  public interface EthTransactionBroadcastDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 fromType = 1;</code>
     * @return The fromType.
     */
    int getFromType();

    /**
     * <code>bytes rlpEncoded = 2;</code>
     * @return The rlpEncoded.
     */
    com.google.protobuf.ByteString getRlpEncoded();
  }
  /**
   * Protobuf type {@code com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO}
   */
  public static final class EthTransactionBroadcastDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO)
      EthTransactionBroadcastDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EthTransactionBroadcastDTO.newBuilder() to construct.
    private EthTransactionBroadcastDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EthTransactionBroadcastDTO() {
      rlpEncoded_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EthTransactionBroadcastDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EthTransactionBroadcastDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              fromType_ = input.readInt32();
              break;
            }
            case 18: {

              rlpEncoded_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_EthTransactionsBroadcastDTO_EthTransactionBroadcastDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_EthTransactionsBroadcastDTO_EthTransactionBroadcastDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.class, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder.class);
    }

    public static final int FROMTYPE_FIELD_NUMBER = 1;
    private int fromType_;
    /**
     * <code>int32 fromType = 1;</code>
     * @return The fromType.
     */
    @java.lang.Override
    public int getFromType() {
      return fromType_;
    }

    public static final int RLPENCODED_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rlpEncoded_;
    /**
     * <code>bytes rlpEncoded = 2;</code>
     * @return The rlpEncoded.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRlpEncoded() {
      return rlpEncoded_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fromType_ != 0) {
        output.writeInt32(1, fromType_);
      }
      if (!rlpEncoded_.isEmpty()) {
        output.writeBytes(2, rlpEncoded_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fromType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fromType_);
      }
      if (!rlpEncoded_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, rlpEncoded_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO)) {
        return super.equals(obj);
      }
      com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO other = (com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO) obj;

      if (getFromType()
          != other.getFromType()) return false;
      if (!getRlpEncoded()
          .equals(other.getRlpEncoded())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROMTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFromType();
      hash = (37 * hash) + RLPENCODED_FIELD_NUMBER;
      hash = (53 * hash) + getRlpEncoded().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO)
        com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_EthTransactionsBroadcastDTO_EthTransactionBroadcastDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_EthTransactionsBroadcastDTO_EthTransactionBroadcastDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.class, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder.class);
      }

      // Construct using com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fromType_ = 0;

        rlpEncoded_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_EthTransactionsBroadcastDTO_EthTransactionBroadcastDTO_descriptor;
      }

      @java.lang.Override
      public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO getDefaultInstanceForType() {
        return com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.getDefaultInstance();
      }

      @java.lang.Override
      public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO build() {
        com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO buildPartial() {
        com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO result = new com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO(this);
        result.fromType_ = fromType_;
        result.rlpEncoded_ = rlpEncoded_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO) {
          return mergeFrom((com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO other) {
        if (other == com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.getDefaultInstance()) return this;
        if (other.getFromType() != 0) {
          setFromType(other.getFromType());
        }
        if (other.getRlpEncoded() != com.google.protobuf.ByteString.EMPTY) {
          setRlpEncoded(other.getRlpEncoded());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int fromType_ ;
      /**
       * <code>int32 fromType = 1;</code>
       * @return The fromType.
       */
      @java.lang.Override
      public int getFromType() {
        return fromType_;
      }
      /**
       * <code>int32 fromType = 1;</code>
       * @param value The fromType to set.
       * @return This builder for chaining.
       */
      public Builder setFromType(int value) {
        
        fromType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fromType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromType() {
        
        fromType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rlpEncoded_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes rlpEncoded = 2;</code>
       * @return The rlpEncoded.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRlpEncoded() {
        return rlpEncoded_;
      }
      /**
       * <code>bytes rlpEncoded = 2;</code>
       * @param value The rlpEncoded to set.
       * @return This builder for chaining.
       */
      public Builder setRlpEncoded(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rlpEncoded_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes rlpEncoded = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRlpEncoded() {
        
        rlpEncoded_ = getDefaultInstance().getRlpEncoded();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO)
    }

    // @@protoc_insertion_point(class_scope:com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO)
    private static final com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO();
    }

    public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EthTransactionBroadcastDTO>
        PARSER = new com.google.protobuf.AbstractParser<EthTransactionBroadcastDTO>() {
      @java.lang.Override
      public EthTransactionBroadcastDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EthTransactionBroadcastDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EthTransactionBroadcastDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EthTransactionBroadcastDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int TXS_FIELD_NUMBER = 1;
  private java.util.List<com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO> txs_;
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO> getTxsList() {
    return txs_;
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTOOrBuilder> 
      getTxsOrBuilderList() {
    return txs_;
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
   */
  @java.lang.Override
  public int getTxsCount() {
    return txs_.size();
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
   */
  @java.lang.Override
  public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO getTxs(int index) {
    return txs_.get(index);
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
   */
  @java.lang.Override
  public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTOOrBuilder getTxsOrBuilder(
      int index) {
    return txs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < txs_.size(); i++) {
      output.writeMessage(1, txs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < txs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, txs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO)) {
      return super.equals(obj);
    }
    com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO other = (com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO) obj;

    if (!getTxsList()
        .equals(other.getTxsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTxsCount() > 0) {
      hash = (37 * hash) + TXS_FIELD_NUMBER;
      hash = (53 * hash) + getTxsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO)
      com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_EthTransactionsBroadcastDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_EthTransactionsBroadcastDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.class, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.Builder.class);
    }

    // Construct using com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTxsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (txsBuilder_ == null) {
        txs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        txsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_EthTransactionsBroadcastDTO_descriptor;
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO getDefaultInstanceForType() {
      return com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO build() {
      com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO buildPartial() {
      com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO result = new com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO(this);
      int from_bitField0_ = bitField0_;
      if (txsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          txs_ = java.util.Collections.unmodifiableList(txs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.txs_ = txs_;
      } else {
        result.txs_ = txsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO) {
        return mergeFrom((com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO other) {
      if (other == com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.getDefaultInstance()) return this;
      if (txsBuilder_ == null) {
        if (!other.txs_.isEmpty()) {
          if (txs_.isEmpty()) {
            txs_ = other.txs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTxsIsMutable();
            txs_.addAll(other.txs_);
          }
          onChanged();
        }
      } else {
        if (!other.txs_.isEmpty()) {
          if (txsBuilder_.isEmpty()) {
            txsBuilder_.dispose();
            txsBuilder_ = null;
            txs_ = other.txs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            txsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTxsFieldBuilder() : null;
          } else {
            txsBuilder_.addAllMessages(other.txs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO> txs_ =
      java.util.Collections.emptyList();
    private void ensureTxsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        txs_ = new java.util.ArrayList<com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO>(txs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTOOrBuilder> txsBuilder_;

    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public java.util.List<com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO> getTxsList() {
      if (txsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(txs_);
      } else {
        return txsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public int getTxsCount() {
      if (txsBuilder_ == null) {
        return txs_.size();
      } else {
        return txsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO getTxs(int index) {
      if (txsBuilder_ == null) {
        return txs_.get(index);
      } else {
        return txsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public Builder setTxs(
        int index, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO value) {
      if (txsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTxsIsMutable();
        txs_.set(index, value);
        onChanged();
      } else {
        txsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public Builder setTxs(
        int index, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder builderForValue) {
      if (txsBuilder_ == null) {
        ensureTxsIsMutable();
        txs_.set(index, builderForValue.build());
        onChanged();
      } else {
        txsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public Builder addTxs(com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO value) {
      if (txsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTxsIsMutable();
        txs_.add(value);
        onChanged();
      } else {
        txsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public Builder addTxs(
        int index, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO value) {
      if (txsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTxsIsMutable();
        txs_.add(index, value);
        onChanged();
      } else {
        txsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public Builder addTxs(
        com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder builderForValue) {
      if (txsBuilder_ == null) {
        ensureTxsIsMutable();
        txs_.add(builderForValue.build());
        onChanged();
      } else {
        txsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public Builder addTxs(
        int index, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder builderForValue) {
      if (txsBuilder_ == null) {
        ensureTxsIsMutable();
        txs_.add(index, builderForValue.build());
        onChanged();
      } else {
        txsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public Builder addAllTxs(
        java.lang.Iterable<? extends com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO> values) {
      if (txsBuilder_ == null) {
        ensureTxsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, txs_);
        onChanged();
      } else {
        txsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public Builder clearTxs() {
      if (txsBuilder_ == null) {
        txs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        txsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public Builder removeTxs(int index) {
      if (txsBuilder_ == null) {
        ensureTxsIsMutable();
        txs_.remove(index);
        onChanged();
      } else {
        txsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder getTxsBuilder(
        int index) {
      return getTxsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTOOrBuilder getTxsOrBuilder(
        int index) {
      if (txsBuilder_ == null) {
        return txs_.get(index);  } else {
        return txsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public java.util.List<? extends com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTOOrBuilder> 
         getTxsOrBuilderList() {
      if (txsBuilder_ != null) {
        return txsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(txs_);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder addTxsBuilder() {
      return getTxsFieldBuilder().addBuilder(
          com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder addTxsBuilder(
        int index) {
      return getTxsFieldBuilder().addBuilder(
          index, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO txs = 1;</code>
     */
    public java.util.List<com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder> 
         getTxsBuilderList() {
      return getTxsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTOOrBuilder> 
        getTxsFieldBuilder() {
      if (txsBuilder_ == null) {
        txsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTO.Builder, com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO.EthTransactionBroadcastDTOOrBuilder>(
                txs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        txs_ = null;
      }
      return txsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO)
  }

  // @@protoc_insertion_point(class_scope:com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO)
  private static final com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO();
  }

  public static com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EthTransactionsBroadcastDTO>
      PARSER = new com.google.protobuf.AbstractParser<EthTransactionsBroadcastDTO>() {
    @java.lang.Override
    public EthTransactionsBroadcastDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EthTransactionsBroadcastDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EthTransactionsBroadcastDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EthTransactionsBroadcastDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.thanos.api.proto.broadcast.EthTransactionsBroadcastDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

