// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package com.thanos.api.proto.broadcast;

public interface GlobalNodeEventsBroadcastDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
   */
  java.util.List<com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO> 
      getGlobalNodeEventsList();
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
   */
  com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO getGlobalNodeEvents(int index);
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
   */
  int getGlobalNodeEventsCount();
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
   */
  java.util.List<? extends com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTOOrBuilder> 
      getGlobalNodeEventsOrBuilderList();
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
   */
  com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTOOrBuilder getGlobalNodeEventsOrBuilder(
      int index);
}
