// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package com.thanos.api.proto.broadcast;

/**
 * Protobuf type {@code com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO}
 */
public final class GlobalNodeEventsBroadcastDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO)
    GlobalNodeEventsBroadcastDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GlobalNodeEventsBroadcastDTO.newBuilder() to construct.
  private GlobalNodeEventsBroadcastDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GlobalNodeEventsBroadcastDTO() {
    globalNodeEvents_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GlobalNodeEventsBroadcastDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GlobalNodeEventsBroadcastDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              globalNodeEvents_ = new java.util.ArrayList<com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO>();
              mutable_bitField0_ |= 0x00000001;
            }
            globalNodeEvents_.add(
                input.readMessage(com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        globalNodeEvents_ = java.util.Collections.unmodifiableList(globalNodeEvents_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_GlobalNodeEventsBroadcastDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_GlobalNodeEventsBroadcastDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.class, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.Builder.class);
  }

  public interface GlobalNodeEventBroadcastDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 fromType = 1;</code>
     * @return The fromType.
     */
    int getFromType();

    /**
     * <code>bytes rlpEncoded = 2;</code>
     * @return The rlpEncoded.
     */
    com.google.protobuf.ByteString getRlpEncoded();
  }
  /**
   * Protobuf type {@code com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO}
   */
  public static final class GlobalNodeEventBroadcastDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO)
      GlobalNodeEventBroadcastDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GlobalNodeEventBroadcastDTO.newBuilder() to construct.
    private GlobalNodeEventBroadcastDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GlobalNodeEventBroadcastDTO() {
      rlpEncoded_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GlobalNodeEventBroadcastDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GlobalNodeEventBroadcastDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              fromType_ = input.readInt32();
              break;
            }
            case 18: {

              rlpEncoded_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_GlobalNodeEventsBroadcastDTO_GlobalNodeEventBroadcastDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_GlobalNodeEventsBroadcastDTO_GlobalNodeEventBroadcastDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.class, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder.class);
    }

    public static final int FROMTYPE_FIELD_NUMBER = 1;
    private int fromType_;
    /**
     * <code>int32 fromType = 1;</code>
     * @return The fromType.
     */
    @java.lang.Override
    public int getFromType() {
      return fromType_;
    }

    public static final int RLPENCODED_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rlpEncoded_;
    /**
     * <code>bytes rlpEncoded = 2;</code>
     * @return The rlpEncoded.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRlpEncoded() {
      return rlpEncoded_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fromType_ != 0) {
        output.writeInt32(1, fromType_);
      }
      if (!rlpEncoded_.isEmpty()) {
        output.writeBytes(2, rlpEncoded_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fromType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fromType_);
      }
      if (!rlpEncoded_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, rlpEncoded_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO)) {
        return super.equals(obj);
      }
      com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO other = (com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO) obj;

      if (getFromType()
          != other.getFromType()) return false;
      if (!getRlpEncoded()
          .equals(other.getRlpEncoded())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROMTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFromType();
      hash = (37 * hash) + RLPENCODED_FIELD_NUMBER;
      hash = (53 * hash) + getRlpEncoded().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO)
        com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_GlobalNodeEventsBroadcastDTO_GlobalNodeEventBroadcastDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_GlobalNodeEventsBroadcastDTO_GlobalNodeEventBroadcastDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.class, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder.class);
      }

      // Construct using com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fromType_ = 0;

        rlpEncoded_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_GlobalNodeEventsBroadcastDTO_GlobalNodeEventBroadcastDTO_descriptor;
      }

      @java.lang.Override
      public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO getDefaultInstanceForType() {
        return com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.getDefaultInstance();
      }

      @java.lang.Override
      public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO build() {
        com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO buildPartial() {
        com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO result = new com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO(this);
        result.fromType_ = fromType_;
        result.rlpEncoded_ = rlpEncoded_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO) {
          return mergeFrom((com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO other) {
        if (other == com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.getDefaultInstance()) return this;
        if (other.getFromType() != 0) {
          setFromType(other.getFromType());
        }
        if (other.getRlpEncoded() != com.google.protobuf.ByteString.EMPTY) {
          setRlpEncoded(other.getRlpEncoded());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int fromType_ ;
      /**
       * <code>int32 fromType = 1;</code>
       * @return The fromType.
       */
      @java.lang.Override
      public int getFromType() {
        return fromType_;
      }
      /**
       * <code>int32 fromType = 1;</code>
       * @param value The fromType to set.
       * @return This builder for chaining.
       */
      public Builder setFromType(int value) {
        
        fromType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fromType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromType() {
        
        fromType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rlpEncoded_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes rlpEncoded = 2;</code>
       * @return The rlpEncoded.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRlpEncoded() {
        return rlpEncoded_;
      }
      /**
       * <code>bytes rlpEncoded = 2;</code>
       * @param value The rlpEncoded to set.
       * @return This builder for chaining.
       */
      public Builder setRlpEncoded(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rlpEncoded_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes rlpEncoded = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRlpEncoded() {
        
        rlpEncoded_ = getDefaultInstance().getRlpEncoded();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO)
    }

    // @@protoc_insertion_point(class_scope:com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO)
    private static final com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO();
    }

    public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GlobalNodeEventBroadcastDTO>
        PARSER = new com.google.protobuf.AbstractParser<GlobalNodeEventBroadcastDTO>() {
      @java.lang.Override
      public GlobalNodeEventBroadcastDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalNodeEventBroadcastDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GlobalNodeEventBroadcastDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalNodeEventBroadcastDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int GLOBALNODEEVENTS_FIELD_NUMBER = 1;
  private java.util.List<com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO> globalNodeEvents_;
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO> getGlobalNodeEventsList() {
    return globalNodeEvents_;
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTOOrBuilder> 
      getGlobalNodeEventsOrBuilderList() {
    return globalNodeEvents_;
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
   */
  @java.lang.Override
  public int getGlobalNodeEventsCount() {
    return globalNodeEvents_.size();
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
   */
  @java.lang.Override
  public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO getGlobalNodeEvents(int index) {
    return globalNodeEvents_.get(index);
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
   */
  @java.lang.Override
  public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTOOrBuilder getGlobalNodeEventsOrBuilder(
      int index) {
    return globalNodeEvents_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < globalNodeEvents_.size(); i++) {
      output.writeMessage(1, globalNodeEvents_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < globalNodeEvents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, globalNodeEvents_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO)) {
      return super.equals(obj);
    }
    com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO other = (com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO) obj;

    if (!getGlobalNodeEventsList()
        .equals(other.getGlobalNodeEventsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGlobalNodeEventsCount() > 0) {
      hash = (37 * hash) + GLOBALNODEEVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getGlobalNodeEventsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO)
      com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_GlobalNodeEventsBroadcastDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_GlobalNodeEventsBroadcastDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.class, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.Builder.class);
    }

    // Construct using com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGlobalNodeEventsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (globalNodeEventsBuilder_ == null) {
        globalNodeEvents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        globalNodeEventsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_GlobalNodeEventsBroadcastDTO_descriptor;
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO getDefaultInstanceForType() {
      return com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO build() {
      com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO buildPartial() {
      com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO result = new com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO(this);
      int from_bitField0_ = bitField0_;
      if (globalNodeEventsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          globalNodeEvents_ = java.util.Collections.unmodifiableList(globalNodeEvents_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.globalNodeEvents_ = globalNodeEvents_;
      } else {
        result.globalNodeEvents_ = globalNodeEventsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO) {
        return mergeFrom((com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO other) {
      if (other == com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.getDefaultInstance()) return this;
      if (globalNodeEventsBuilder_ == null) {
        if (!other.globalNodeEvents_.isEmpty()) {
          if (globalNodeEvents_.isEmpty()) {
            globalNodeEvents_ = other.globalNodeEvents_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGlobalNodeEventsIsMutable();
            globalNodeEvents_.addAll(other.globalNodeEvents_);
          }
          onChanged();
        }
      } else {
        if (!other.globalNodeEvents_.isEmpty()) {
          if (globalNodeEventsBuilder_.isEmpty()) {
            globalNodeEventsBuilder_.dispose();
            globalNodeEventsBuilder_ = null;
            globalNodeEvents_ = other.globalNodeEvents_;
            bitField0_ = (bitField0_ & ~0x00000001);
            globalNodeEventsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGlobalNodeEventsFieldBuilder() : null;
          } else {
            globalNodeEventsBuilder_.addAllMessages(other.globalNodeEvents_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO> globalNodeEvents_ =
      java.util.Collections.emptyList();
    private void ensureGlobalNodeEventsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        globalNodeEvents_ = new java.util.ArrayList<com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO>(globalNodeEvents_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTOOrBuilder> globalNodeEventsBuilder_;

    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public java.util.List<com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO> getGlobalNodeEventsList() {
      if (globalNodeEventsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(globalNodeEvents_);
      } else {
        return globalNodeEventsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public int getGlobalNodeEventsCount() {
      if (globalNodeEventsBuilder_ == null) {
        return globalNodeEvents_.size();
      } else {
        return globalNodeEventsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO getGlobalNodeEvents(int index) {
      if (globalNodeEventsBuilder_ == null) {
        return globalNodeEvents_.get(index);
      } else {
        return globalNodeEventsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public Builder setGlobalNodeEvents(
        int index, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO value) {
      if (globalNodeEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGlobalNodeEventsIsMutable();
        globalNodeEvents_.set(index, value);
        onChanged();
      } else {
        globalNodeEventsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public Builder setGlobalNodeEvents(
        int index, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder builderForValue) {
      if (globalNodeEventsBuilder_ == null) {
        ensureGlobalNodeEventsIsMutable();
        globalNodeEvents_.set(index, builderForValue.build());
        onChanged();
      } else {
        globalNodeEventsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public Builder addGlobalNodeEvents(com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO value) {
      if (globalNodeEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGlobalNodeEventsIsMutable();
        globalNodeEvents_.add(value);
        onChanged();
      } else {
        globalNodeEventsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public Builder addGlobalNodeEvents(
        int index, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO value) {
      if (globalNodeEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGlobalNodeEventsIsMutable();
        globalNodeEvents_.add(index, value);
        onChanged();
      } else {
        globalNodeEventsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public Builder addGlobalNodeEvents(
        com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder builderForValue) {
      if (globalNodeEventsBuilder_ == null) {
        ensureGlobalNodeEventsIsMutable();
        globalNodeEvents_.add(builderForValue.build());
        onChanged();
      } else {
        globalNodeEventsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public Builder addGlobalNodeEvents(
        int index, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder builderForValue) {
      if (globalNodeEventsBuilder_ == null) {
        ensureGlobalNodeEventsIsMutable();
        globalNodeEvents_.add(index, builderForValue.build());
        onChanged();
      } else {
        globalNodeEventsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public Builder addAllGlobalNodeEvents(
        java.lang.Iterable<? extends com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO> values) {
      if (globalNodeEventsBuilder_ == null) {
        ensureGlobalNodeEventsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, globalNodeEvents_);
        onChanged();
      } else {
        globalNodeEventsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public Builder clearGlobalNodeEvents() {
      if (globalNodeEventsBuilder_ == null) {
        globalNodeEvents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        globalNodeEventsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public Builder removeGlobalNodeEvents(int index) {
      if (globalNodeEventsBuilder_ == null) {
        ensureGlobalNodeEventsIsMutable();
        globalNodeEvents_.remove(index);
        onChanged();
      } else {
        globalNodeEventsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder getGlobalNodeEventsBuilder(
        int index) {
      return getGlobalNodeEventsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTOOrBuilder getGlobalNodeEventsOrBuilder(
        int index) {
      if (globalNodeEventsBuilder_ == null) {
        return globalNodeEvents_.get(index);  } else {
        return globalNodeEventsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public java.util.List<? extends com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTOOrBuilder> 
         getGlobalNodeEventsOrBuilderList() {
      if (globalNodeEventsBuilder_ != null) {
        return globalNodeEventsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(globalNodeEvents_);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder addGlobalNodeEventsBuilder() {
      return getGlobalNodeEventsFieldBuilder().addBuilder(
          com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder addGlobalNodeEventsBuilder(
        int index) {
      return getGlobalNodeEventsFieldBuilder().addBuilder(
          index, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO globalNodeEvents = 1;</code>
     */
    public java.util.List<com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder> 
         getGlobalNodeEventsBuilderList() {
      return getGlobalNodeEventsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTOOrBuilder> 
        getGlobalNodeEventsFieldBuilder() {
      if (globalNodeEventsBuilder_ == null) {
        globalNodeEventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTO.Builder, com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO.GlobalNodeEventBroadcastDTOOrBuilder>(
                globalNodeEvents_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        globalNodeEvents_ = null;
      }
      return globalNodeEventsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO)
  }

  // @@protoc_insertion_point(class_scope:com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO)
  private static final com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO();
  }

  public static com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GlobalNodeEventsBroadcastDTO>
      PARSER = new com.google.protobuf.AbstractParser<GlobalNodeEventsBroadcastDTO>() {
    @java.lang.Override
    public GlobalNodeEventsBroadcastDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GlobalNodeEventsBroadcastDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GlobalNodeEventsBroadcastDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GlobalNodeEventsBroadcastDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.thanos.api.proto.broadcast.GlobalNodeEventsBroadcastDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

