// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package com.thanos.api.proto.broadcast;

/**
 * Protobuf type {@code com.thanos.api.proto.broadcast.NodesBroadcastDTO}
 */
public final class NodesBroadcastDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.thanos.api.proto.broadcast.NodesBroadcastDTO)
    NodesBroadcastDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NodesBroadcastDTO.newBuilder() to construct.
  private NodesBroadcastDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NodesBroadcastDTO() {
    nodes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NodesBroadcastDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NodesBroadcastDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              nodes_ = new java.util.ArrayList<com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO>();
              mutable_bitField0_ |= 0x00000001;
            }
            nodes_.add(
                input.readMessage(com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        nodes_ = java.util.Collections.unmodifiableList(nodes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_NodesBroadcastDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_NodesBroadcastDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.thanos.api.proto.broadcast.NodesBroadcastDTO.class, com.thanos.api.proto.broadcast.NodesBroadcastDTO.Builder.class);
  }

  public interface NodeBroadcastDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string ip = 2;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 2;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int32 port = 3;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO}
   */
  public static final class NodeBroadcastDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO)
      NodeBroadcastDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeBroadcastDTO.newBuilder() to construct.
    private NodeBroadcastDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeBroadcastDTO() {
      id_ = "";
      ip_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NodeBroadcastDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodeBroadcastDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_NodesBroadcastDTO_NodeBroadcastDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_NodesBroadcastDTO_NodeBroadcastDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.class, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 2;</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 2;</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>int32 port = 3;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(3, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO)) {
        return super.equals(obj);
      }
      com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO other = (com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO)
        com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_NodesBroadcastDTO_NodeBroadcastDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_NodesBroadcastDTO_NodeBroadcastDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.class, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder.class);
      }

      // Construct using com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        ip_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_NodesBroadcastDTO_NodeBroadcastDTO_descriptor;
      }

      @java.lang.Override
      public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO getDefaultInstanceForType() {
        return com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.getDefaultInstance();
      }

      @java.lang.Override
      public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO build() {
        com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO buildPartial() {
        com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO result = new com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO(this);
        result.id_ = id_;
        result.ip_ = ip_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO) {
          return mergeFrom((com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO other) {
        if (other == com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 2;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 3;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 3;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO)
    }

    // @@protoc_insertion_point(class_scope:com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO)
    private static final com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO();
    }

    public static com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeBroadcastDTO>
        PARSER = new com.google.protobuf.AbstractParser<NodeBroadcastDTO>() {
      @java.lang.Override
      public NodeBroadcastDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeBroadcastDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeBroadcastDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeBroadcastDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NODES_FIELD_NUMBER = 1;
  private java.util.List<com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO> nodes_;
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO> getNodesList() {
    return nodes_;
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTOOrBuilder> 
      getNodesOrBuilderList() {
    return nodes_;
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
   */
  @java.lang.Override
  public int getNodesCount() {
    return nodes_.size();
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
   */
  @java.lang.Override
  public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO getNodes(int index) {
    return nodes_.get(index);
  }
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
   */
  @java.lang.Override
  public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTOOrBuilder getNodesOrBuilder(
      int index) {
    return nodes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < nodes_.size(); i++) {
      output.writeMessage(1, nodes_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < nodes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, nodes_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.thanos.api.proto.broadcast.NodesBroadcastDTO)) {
      return super.equals(obj);
    }
    com.thanos.api.proto.broadcast.NodesBroadcastDTO other = (com.thanos.api.proto.broadcast.NodesBroadcastDTO) obj;

    if (!getNodesList()
        .equals(other.getNodesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNodesCount() > 0) {
      hash = (37 * hash) + NODES_FIELD_NUMBER;
      hash = (53 * hash) + getNodesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.thanos.api.proto.broadcast.NodesBroadcastDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.thanos.api.proto.broadcast.NodesBroadcastDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.thanos.api.proto.broadcast.NodesBroadcastDTO)
      com.thanos.api.proto.broadcast.NodesBroadcastDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_NodesBroadcastDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_NodesBroadcastDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanos.api.proto.broadcast.NodesBroadcastDTO.class, com.thanos.api.proto.broadcast.NodesBroadcastDTO.Builder.class);
    }

    // Construct using com.thanos.api.proto.broadcast.NodesBroadcastDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNodesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (nodesBuilder_ == null) {
        nodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        nodesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.thanos.api.proto.broadcast.BroadcastGrpcTransport.internal_static_com_thanos_api_proto_broadcast_NodesBroadcastDTO_descriptor;
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.NodesBroadcastDTO getDefaultInstanceForType() {
      return com.thanos.api.proto.broadcast.NodesBroadcastDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.NodesBroadcastDTO build() {
      com.thanos.api.proto.broadcast.NodesBroadcastDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.thanos.api.proto.broadcast.NodesBroadcastDTO buildPartial() {
      com.thanos.api.proto.broadcast.NodesBroadcastDTO result = new com.thanos.api.proto.broadcast.NodesBroadcastDTO(this);
      int from_bitField0_ = bitField0_;
      if (nodesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.nodes_ = nodes_;
      } else {
        result.nodes_ = nodesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.thanos.api.proto.broadcast.NodesBroadcastDTO) {
        return mergeFrom((com.thanos.api.proto.broadcast.NodesBroadcastDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.thanos.api.proto.broadcast.NodesBroadcastDTO other) {
      if (other == com.thanos.api.proto.broadcast.NodesBroadcastDTO.getDefaultInstance()) return this;
      if (nodesBuilder_ == null) {
        if (!other.nodes_.isEmpty()) {
          if (nodes_.isEmpty()) {
            nodes_ = other.nodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNodesIsMutable();
            nodes_.addAll(other.nodes_);
          }
          onChanged();
        }
      } else {
        if (!other.nodes_.isEmpty()) {
          if (nodesBuilder_.isEmpty()) {
            nodesBuilder_.dispose();
            nodesBuilder_ = null;
            nodes_ = other.nodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            nodesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNodesFieldBuilder() : null;
          } else {
            nodesBuilder_.addAllMessages(other.nodes_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.thanos.api.proto.broadcast.NodesBroadcastDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.thanos.api.proto.broadcast.NodesBroadcastDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO> nodes_ =
      java.util.Collections.emptyList();
    private void ensureNodesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        nodes_ = new java.util.ArrayList<com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO>(nodes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTOOrBuilder> nodesBuilder_;

    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public java.util.List<com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO> getNodesList() {
      if (nodesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nodes_);
      } else {
        return nodesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public int getNodesCount() {
      if (nodesBuilder_ == null) {
        return nodes_.size();
      } else {
        return nodesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO getNodes(int index) {
      if (nodesBuilder_ == null) {
        return nodes_.get(index);
      } else {
        return nodesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public Builder setNodes(
        int index, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.set(index, value);
        onChanged();
      } else {
        nodesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public Builder setNodes(
        int index, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.set(index, builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public Builder addNodes(com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.add(value);
        onChanged();
      } else {
        nodesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public Builder addNodes(
        int index, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.add(index, value);
        onChanged();
      } else {
        nodesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public Builder addNodes(
        com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.add(builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public Builder addNodes(
        int index, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.add(index, builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public Builder addAllNodes(
        java.lang.Iterable<? extends com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO> values) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nodes_);
        onChanged();
      } else {
        nodesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public Builder clearNodes() {
      if (nodesBuilder_ == null) {
        nodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        nodesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public Builder removeNodes(int index) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.remove(index);
        onChanged();
      } else {
        nodesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder getNodesBuilder(
        int index) {
      return getNodesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTOOrBuilder getNodesOrBuilder(
        int index) {
      if (nodesBuilder_ == null) {
        return nodes_.get(index);  } else {
        return nodesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public java.util.List<? extends com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTOOrBuilder> 
         getNodesOrBuilderList() {
      if (nodesBuilder_ != null) {
        return nodesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nodes_);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder addNodesBuilder() {
      return getNodesFieldBuilder().addBuilder(
          com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder addNodesBuilder(
        int index) {
      return getNodesFieldBuilder().addBuilder(
          index, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
     */
    public java.util.List<com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder> 
         getNodesBuilderList() {
      return getNodesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTOOrBuilder> 
        getNodesFieldBuilder() {
      if (nodesBuilder_ == null) {
        nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO.Builder, com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTOOrBuilder>(
                nodes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        nodes_ = null;
      }
      return nodesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.thanos.api.proto.broadcast.NodesBroadcastDTO)
  }

  // @@protoc_insertion_point(class_scope:com.thanos.api.proto.broadcast.NodesBroadcastDTO)
  private static final com.thanos.api.proto.broadcast.NodesBroadcastDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.thanos.api.proto.broadcast.NodesBroadcastDTO();
  }

  public static com.thanos.api.proto.broadcast.NodesBroadcastDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NodesBroadcastDTO>
      PARSER = new com.google.protobuf.AbstractParser<NodesBroadcastDTO>() {
    @java.lang.Override
    public NodesBroadcastDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NodesBroadcastDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NodesBroadcastDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NodesBroadcastDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.thanos.api.proto.broadcast.NodesBroadcastDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

