// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package com.thanos.api.proto.broadcast;

public interface NodesBroadcastDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.broadcast.NodesBroadcastDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
   */
  java.util.List<com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO> 
      getNodesList();
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
   */
  com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO getNodes(int index);
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
   */
  java.util.List<? extends com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTOOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTO nodes = 1;</code>
   */
  com.thanos.api.proto.broadcast.NodesBroadcastDTO.NodeBroadcastDTOOrBuilder getNodesOrBuilder(
      int index);
}
